version: '3.8'

services:
  # Frontend Development Server
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000/api
      - VITE_WS_URL=ws://localhost:3000
    depends_on:
      - backend

  # Backend API Server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env.local
    depends_on:
      - ai-service
    command: npm run dev

  # AI Service (CPU version for development)
  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./ai-service:/app
      - huggingface_cache:/root/.cache/huggingface
    environment:
      - REDIS_HOST=host.docker.internal  # Use your existing Redis server
      - REDIS_PORT=6379
      - DEVICE=cpu  # Use CPU for development
    command: python main.py

volumes:
  huggingface_cache: